### ISSUE TITLE
[Feature] Option to set a background image from URL!

### ISSUE THREAD

**Issue by danimesq** [PRATAP-KUMAR/ubuntu-gdm-set-background#31]
This means `wget` should be involved under the hood.

For example:
1. `sudo bash ubuntu-gdm-set-background --image https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaBcL52vY5CM9Ia1YLgWfaxFV7EcABk_MGjw5vMmLtvtmSVG4-wjwwAAugOS60iQE1pjS59nnfpnFPf2TfxGFU3bkWmk_w=w4096-h2304`
2. `sudo bash ubuntu-gdm-set-background --image https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCTV97rHRociSzU4sVoIGWb6pvyig74oxFHCN4qubQRQT8fn5aTgi2HArFgHB-C5kjCv5oM-k1fm1fuxx7G9_dYn8qxVg=w4096-h2304`

# Tasks

- [ ] --image cmd will detect if `$2` begin with "/" or "http"; otherwise, will tell it is invalid and suggest how to use.
- [ ] if `$2` begin with "/", do as currently it does but now: copying the src img as backup and then applying from it. If it begin with "http", run wget with `/usr/lib/ubuntu-gdm-set-background/bg/{filename}` as destination, then set from it. 
- [ ] Should know if there's Internet connection, otherwise fail. Also, should ensure /bg/ isn't empty after running wget.
- [ ] On begin of the --image function, when no error, always rmv+recreate /bg/ folder.

**Comment by PRATAP-KUMAR** [comment]
IMHO, setting background image from url will not work. As it required internet by that time when system boots and ready with GDM.

**Comment by danimesq** [comment]
I mean, downloading that image once and storing it "permanently" `/usr/lib/ubuntu-gdm-set-background`, overwriting everytime user want to change/update the bg.

**Comment by danimesq** [comment]
I feel me inspired and energized enough to try that right today <3

**Comment by PRATAP-KUMAR** [comment]
Ok all the best. That seems possible.

**Comment by PRATAP-KUMAR** [comment]
can I have your email id please?

**Comment by danimesq** [comment]
mesquitadaniella@proton.me

**Comment by PRATAP-KUMAR** [comment]
Ok thanks, I copied it. You can delete it.

**Comment by danimesq** [comment]
Can delete the last two messages, two. Once read, I'll delete this comment too.
